### ISSUE TITLE
Unhandled exception when clicking "Refresh" in source folder dialogue

### ISSUE THREAD

**Issue by Jaegrqualm** [DrWhoCares/imgdanke#1]
Steps to reproduce:

1. Open program
2. Don't set the source folder path
3. Click "Refresh" in the "Files in Source Folder" portion of the window
4. Unhandled Exception

Fortunately, clicking continue in the dialoue that pops up lets the program continue running, seemingly without issue.

**Comment by DrWhoCares** [comment]
Fixed in 946187ea
Released in v1.2020.7.14
