### ISSUE TITLE
Clicking "Apply" when magick.exe is not present results in an uncancellable hang

### ISSUE THREAD

**Issue by Jaegrqualm** [DrWhoCares/imgdanke#6]
Steps to reproduce:
1. Open program, with at least the 'download magick' dialogue appearing
2. Set filepaths
3. Click a preset
4. Click "Apply"
5. Attempt to click "Cancel"
6. Nothing happens

May be platform specific (WINE 5.12), needs repro. When hanging in this manner, the program uses a sizeable amount of CPU resources. 
When doing this over and over again after closing the program while frozen, the program appears to move on to the next file to be worked on, despite the list being selected just the same, and there being no files in the destination folder.

**Comment by DrWhoCares** [comment]
Potentially fixed in b1938adb
Released in v1.2020.7.14
@Jaegrqualm Please verify the issue has been fixed.

**Comment by Jaegrqualm** [comment]
It appears that the "Apply" button is no longer clickable under any circumstances when the required .exe files aren't present. At this point, it seems to be fixed for me.

**Comment by DrWhoCares** [comment]
Correct, there were a number of missed steps in verification that caused verification to pass when it shouldn't have. These have been remedied, along with properly allowing you to run a single command (before b1938ad it was not possible to run without both commands being entirely valid).
