### ISSUE TITLE
Pre-release issues

### ISSUE THREAD

**Issue by Jaegrqualm** [DrWhoCares/imgdanke#85]
This is a list of bugs from a private pre-release build. Doc wanted it here, so here it is.

- [x] pingo throwing 'bad command' in its log, while 1.2021.1.2 build works

- [x] clicking 'include PSDs' without paths set results in a crash

- [x] setting 'delete originals' and 'output to new folder' results in new images being dumped in the output 

- [x] selecting the checkbox 'add tags to new output folder', selecting the checkboxes within it, and then unchecking  the root checkbox results in the tags still being applied to the new output folder

- [x] if 'delete originals' is selected, and the new file has the same name as the old file, there ends up being no file selected in the filepicker while the 'start' button is still enabled

- [x] the combinations of 'delete originals', 'replace originals', filename tags, separate output folders, and related settings appear to behave confusingly

**Comment by DrWhoCares** [comment]
Fixed in 4632e049, b7e2c169, and 887ec22d
Released in v1.2021.3.1
