### ISSUE TITLE
Temp directory is being set to c:\imagedanke, causing it to delete everything

### ISSUE THREAD

**Issue by ChronoStriker1** [DrWhoCares/imgdanke#93]
1.2021.3.25 - temp folder seems to be set to the path of the executable so when run it thinks the folder is not empty and gives the option to delete, which deletes everything except the running executable.

**Comment by DrWhoCares** [comment]
That seems *very* odd.
What's your setup?
- Where is imgdanke extracted to?
- What drive is your SourceFolderPath on? Like, C:\ etc.
- What drive is your OutputFolderPath on?
- What other settings are you using, such as output to new folder, replace originals, delete originals, etc. A screenshot is usually best, including a screenshot of the OutputSettings window, if you're using anything in it.

**Comment by DrWhoCares** [comment]
Nevermind @ChronoStriker1 it turns out I misremembered that the TEMP_FOLDER_NAME variable is "imgdanke/" now, not "danketmp/" or whatever I had it previously set to.
Thought there was an underscore at the beginning too. I'll release a fix after work.

**Comment by DrWhoCares** [comment]
Fixed in 47c36f91
Released in v1.2021.3.29
