### ISSUE TITLE
v1.2021.7.10 - magick command keeps reprocessing the same files

### ISSUE THREAD

**Issue by DrWhoCares** [DrWhoCares/imgdanke#97]
I can't reproduce this on my end, so if someone else can, let me know so I can debug it.
It could be a path length issue, a cross-drive (source is one drive, output is another) issue, file permissions issue, codepage issue, imagemagick bug (update to imagemagick may fix it), etc.

Nothing seems to point towards any issues in particular, so nothing can be done until this bug can be reproduced and tested.

**Comment by Shellshock123** [comment]
This issue is happening to me as well. Its converting to 8bpp over and over again.

**Comment by DrWhoCares** [comment]
I need more information.
Tell me what your current pingo version is, current imagemagick version, and I need to know your imgdanke settings.
Particularly, the Source Folder Path, Output Folder Path, Include Subfolders, etc.

**Comment by DrWhoCares** [comment]
This is caused by having a large number of files set to process. I don't know the specific amount, at least 200, it's likely much lower than that amount though.
I don't know why yet. When I originally made the fix for the subfolders problem, I was testing on over 200 files, but the files were spread throughout several folders, with around 30 per folder.

**Comment by DrWhoCares** [comment]
Fixed in 404e62a
Released in v1.2021.7.20
