### ISSUE TITLE
magick command not working? 

### ISSUE THREAD

**Issue by Shellshock123** [DrWhoCares/imgdanke#99]
I put the magick.exe files and loose files in the same folder as imgdanke.exe. 

But it just skips it over. It says processing magick.exe and skips its over. The pingo command works and when it does complete it, it is optimized but not converted to 8bpp. the coloured page remains coloured as well.

**Comment by DrWhoCares** [comment]
What imagemagick version, what pingo version, what imgdanke version, send me your user config file as well.

**Comment by Shellshock123** [comment]
All of it is the latest version at the time of writing.

> "LastWindowLocation":{"IsEmpty":false,"X":896,"Y":240},"ShouldStartMaximized":false,"ShouldCheckForUpdatesOnStartup":true,"ShouldDisableFailedToCheckForUpdatesMessage":false,"ShouldSuppressPingoNotFoundWarning":false,"LastWindowSize":{"Is

Microsoft Visual Studio is opening instead of text editor.

**Comment by DrWhoCares** [comment]
Provide the file, not a broken snippet of it.

**Comment by Shellshock123** [comment]
[imgdanke_UserConfig.zip](https://github.com/DrWhoCares/imgdanke/files/8784187/imgdanke_UserConfig.zip)

**Comment by DrWhoCares** [comment]
For some reason your user config begins with a `
It shouldn't. Also for some reason your imagemagick path is a full path, but pingo isn't.
I feel like something got messed up when you changed something at some point. Moved directories or something else.
Try deleting the user config and see if it fixes the issue.

**Comment by DrWhoCares** [comment]
Issue was solved by following the guide [here](https://github.com/DrWhoCares/imgdanke/wiki/ImageMagick#installation-instructions) and installing magick according to what that guide says, rather than putting in the same folder as imgdanke.exe.
